pydihaum/idihaum/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("reader/<int:reader_id>/", views.reader, name= "Reader"),
    path("user/<int:user_id>/", views.user, name= "User"),
    ]

pydihaum/pydihaum/urls.py
from django.contrib import admin
from django.urls import path, include
# from idihaum import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("idihaum.urls")),
]

pydihaum/idihaum/models.py
from django.db import models


class Access_reader(models.Model):
    label = models.CharField(max_length=255)
    active = models.BooleanField(default=True)
    listen_topic = models.CharField(max_length=255) # topic recevant l ID de la carte
    answer_topic = models.CharField(max_length=255) # topic action du reader
    message_topic = models.CharField(max_length=255) # message pour action du reader

    def __str__(self):
        return str(self.label)


class User(models.Model):
    name = models.CharField(blank=True, null=True, max_length=255)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    allowed_accesses = models.ManyToManyField(Access_reader, blank=True)

    def __str__(self):
        return self.name


class Card(models.Model):
    uid = models.CharField(unique=True, max_length=255)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    label = models.CharField(max_length=255)

    def __str__(self):
        return str(self.uid) + ' - ' + str(self.user)


class Log(models.Model):
    card = models.ForeignKey(Card, null=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    reader = models.ForeignKey(Access_reader, null=True, on_delete=models.SET_NULL)
    unknown_card = models.CharField(blank=True, null=True, max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    comment = models.CharField(blank=True, null=True, max_length=255)

    def __str__(self):
        return str(self.user) + ' at ' + str(self.created_at)

pydihaum/idihaum/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

from .models import Access_reader, User, Card


def index(request):
    users_list = User.objects.all()
    reader_list = Access_reader.objects.all()

    template = loader.get_template("idihaum/index.html")
    context = {
        "users_list": users_list,
        "reader_list": reader_list,
    }
    return HttpResponse(template.render(context, request))


def reader(request, reader_id):
    the_reader = Access_reader.objects.get(id=reader_id)
    template = loader.get_template("idihaum/reader.html")
    context = {
		"the_reader": the_reader,
    }
    return HttpResponse(template.render(context, request))


def user (request, user_id):
    the_user = User.objects.get(id = user_id)
    template = loader.get_template("idihaum/user.html")
    context = {
		"the_user": the_user,
    }
    return HttpResponse(template.render(context, request))

pydihaum/idihaum/templates/idihaum/index.html
{% load static %}
<!DOCTYPE html>
<html lang="fr-FR">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width">
   <title>IdiHaum acess matrix</title>
   <link href="{% static 'idihaum/minimal-table.css' %}"rel="stylesheet" type="text/css">
</head>
    <body>
        <h1>IdiHaum user matrix</h1>
        <table>
            {% if reader_list %}
            <tr>
                <td><b>User / Reader </b></td>
                {% for reader in reader_list %}
                <td><a href="/reader/{{ reader.id }}/">{{ reader.label }}</a></td>
                {% endfor %}
            </tr>
            {% endif %}
            {% if users_list %}
                {% for user in users_list %}
                <tr>
                    <td><a href="/user/{{ user.id }}/">{{ user.name }}</a></td>

                        {% for reader in user.allowed_accesses.all %}
                        <td><a href="/reader/{{ reader.id }}/">{{ reader.label }}</a></td>
                        {% endfor %}

                </tr>
                {% endfor %}
            {% endif %}
        </table>
    </body>
</html>

pydihaum/idihaum/templates/idihaum/reader.html
{% load static %}
<!DOCTYPE html>
<html lang="fr-FR">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width">
   <title>IdiHaum reader matrix</title>
   <link href="{% static 'idihaum/minimal-table.css' %}"rel="stylesheet" type="text/css">
</head>
    <body>
	<a href="/"> <- index</a>
	{% if the_reader %}
        <h1>{{ the_reader.label }} access matrix</h1>
        <table>
	<tr>
		<td><b>{{ the_reader.label }}</b></td>
			{% for user in the_reader.user_set.all %}
			<td><a href="/user/{{ user.id }}/">{{ user.name }}</a></td>
			{% endfor %}
		</tr>
	</table>
	<b>the_reader.Id_topic </b>{{the_reader.Id_topic}}</br>
	<b>the_reader.Answer_topic </b>{{the_reader.Answer_topic}}</br>
	<b>the_reader.Message_topic </b>{{the_reader.Message_topic}}
        {% else %}
		no reader
        {% endif %}
    </body>
</html>

pydihaum/idihaum/templates/idihaum/user.html
{% load static %}
<!DOCTYPE html>
<html lang="fr-FR">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width">
   <title>IdiHaum user matrix</title>
   <link href="{% static 'idihaum/minimal-table.css' %}"rel="stylesheet" type="text/css">
</head>
    <body>
	<a href="/"> <- index</a>
	{% if the_user %}
        <h1>{{ the_user.name }} access matrix</h1>
        <table>
		<td>{{ the_user.name }}</td>
		{% for reader in the_user.allowed_accesses.all %}
			<td><a href="/reader/{{ reader.id }}/">{{ reader.label }}</a></td>
		{% endfor %}
        </table>

        {% else %}
		no user
        {% endif %}
    </body>
</html>